name: esports_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
